image: node:16.9.1
variables:
  SLACK_WEBHOOK_URL_REQUEST: "<SLACK_WEBHOOK_URL_REQUEST>"
  SLACK_CHANNEL_TARGET: t"<SLACK_CHANNEL_TARGET>"
  NOTIFICATION_TYPE: merge
slack-send-notification:
  script:
    - bash .slack/scripts/slack-notification.sh
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event' && $CI_MERGE_REQUEST_TARGET_BRANCH_PROTECTED
